function compare_sweep_profiles_auto(summaryFile)
%COMPARE_SWEEP_PROFILES_AUTO
% Load sweep_summary.mat and create publication-quality overlay plots
% for carrier density, charge density, electric field, potential,
% band energies, and recombination rates.
%
% Usage:
%   compare_sweep_profiles_auto('sweep_summary_20260113.mat')
%
%   1. Set the sweep_name and sweep_vals to define which variable to compare
%   2. Set fixed parameters for all other variables
%   3. Run the script
%
% Profiles are loaded from the sweep_summary.mat file generated by
% postprocess_sweep_profiles.m

close all;

%% ========================================================================
%  USER CONFIGURATION
%% ========================================================================

% ---- Sweep configuration ----
% Choose which variable to sweep for comparison:
%   "junction_depth" | "sp_r" | "eta_sf" | "EF" | "Phi_R_offset"
sweep_name = "junction_depth";

% Values to overlay (typically 3-5 runs for clarity)
sweep_vals = [200, 300, 400];   % example: junction depth (nm)

% ---- Fixed parameters (held constant while sweeping one variable) ----
SF_flag_fixed        = 1;
eta_sf_fixed         = 2.0;      % if SF_flag_fixed==0, eta is forced to 0
junction_depth_fixed = 300;      % nm (ignored if sweeping junction_depth)
sp_r_fixed           = 1e5;      % cm/s (ignored if sweeping sp_r)
EF_fixed             = -4.223;   % eV (ignored if sweeping EF)
Phi_R_offset_fixed   = -0.0539;  % eV (ignored if sweeping Phi_R_offset)

% ---- Plot settings ----
xrange = [1.795e5, 1.804e5];  % x-axis range in nm (emitter/SF region)

% Which plots to generate:
do_carrier_density = true;       % n, p (log y-axis)
do_charge_density  = true;       % rho
do_electric_field  = true;       % F
do_potential       = true;       % V
do_band_energies   = true;       % Ecb, Evb, Ef
do_recombination   = true;       % btb, SRH, vsr

% Figure size [width, height] in pixels
fig_size = [600, 400];

% Tolerance for parameter matching
tol = 0.01;

%% ========================================================================
%  COLOR SCHEME - Visually distinct, poster-friendly
%% ========================================================================

colors = [
    0.00, 0.45, 0.70;   % blue
    0.90, 0.60, 0.00;   % orange
    0.00, 0.60, 0.50;   % teal
    0.80, 0.40, 0.70;   % purple
    0.60, 0.60, 0.00;   % olive
    0.80, 0.00, 0.00;   % red
];

%% ========================================================================
%  LOAD SUMMARY DATA
%% ========================================================================

fprintf('Loading %s...\n', summaryFile);
data = load(summaryFile, 'summary');
summary = data.summary;
runs = summary.runs;
T = summary.table;
fprintf('Loaded %d runs (%d successful)\n', length(runs), summary.n_success);

% Filter to successful runs only
success_mask = strcmp(T.status, 'success');
T_success = T(success_mask, :);

%% ========================================================================
%  FIND MATCHING RUNS
%% ========================================================================

fprintf('\n=== Finding runs to compare ===\n');

plot_data = struct([]);

for k = 1:numel(sweep_vals)
    % Build parameter set for this run
    p = struct();
    p.SF_flag = SF_flag_fixed;
    
    if p.SF_flag == 0
        p.eta_sf = 0;
    else
        p.eta_sf = eta_sf_fixed;
    end
    
    p.junction_depth = junction_depth_fixed;
    p.sp_r           = sp_r_fixed;
    p.EF_emitter     = EF_fixed;
    p.Phi_R_offset   = Phi_R_offset_fixed;
    
    % Override swept variable
    switch sweep_name
        case "junction_depth"
            p.junction_depth = sweep_vals(k);
        case "sp_r"
            p.sp_r = sweep_vals(k);
        case "eta_sf"
            p.eta_sf = sweep_vals(k);
        case "EF"
            p.EF_emitter = sweep_vals(k);
        case "Phi_R_offset"
            p.Phi_R_offset = sweep_vals(k);
        otherwise
            error("Unknown sweep_name: %s", sweep_name);
    end
    
    % Find matching run in table
    mask = (T_success.SF_flag == p.SF_flag) & ...
           (abs(T_success.eta_SF - p.eta_sf) < tol) & ...
           (T_success.junction_depth_nm == p.junction_depth) & ...
           (abs(T_success.SRV_cm_s - p.sp_r) / p.sp_r < tol) & ...
           (abs(T_success.EF_emitter_eV - p.EF_emitter) < tol) & ...
           (abs(T_success.Phi_R_offset_eV - p.Phi_R_offset) < tol);
    
    idx = find(mask);
    
    if isempty(idx)
        warning('No matching run found for sweep_val = %g', sweep_vals(k));
        continue;
    end
    
    run_idx = T_success.run_number(idx(1));
    r = runs(run_idx);
    
    % Check if profiles exist
    if isempty(r.profiles.x_nm)
        warning('Run %d has no profiles extracted', run_idx);
        continue;
    end
    
    % Store data for plotting
    idx_plot = numel(plot_data) + 1;
    plot_data(idx_plot).label = make_label(p, sweep_name);
    
    color_idx = mod(k-1, size(colors, 1)) + 1;
    plot_data(idx_plot).color = colors(color_idx, :);
    
    plot_data(idx_plot).x     = r.profiles.x_nm;
    plot_data(idx_plot).x_sub = r.profiles.x_sub_nm;
    plot_data(idx_plot).n     = r.profiles.n;
    plot_data(idx_plot).p     = r.profiles.p;
    plot_data(idx_plot).rho   = r.profiles.rho;
    plot_data(idx_plot).F     = r.profiles.F;
    plot_data(idx_plot).V     = r.profiles.V;
    plot_data(idx_plot).Ecb   = r.profiles.Ecb;
    plot_data(idx_plot).Evb   = r.profiles.Evb;
    plot_data(idx_plot).Efn   = r.profiles.Efn;
    plot_data(idx_plot).Efp   = r.profiles.Efp;
    plot_data(idx_plot).r_btb = r.profiles.r_btb;
    plot_data(idx_plot).r_srh = r.profiles.r_srh;
    plot_data(idx_plot).r_vsr = r.profiles.r_vsr;
    
    fprintf('  Found: %s (run %d)\n', plot_data(idx_plot).label, run_idx);
end

if isempty(plot_data)
    error('No valid runs found to plot. Check parameters.');
end

fprintf('\nPlotting %d runs\n\n', numel(plot_data));

%% ========================================================================
%  GENERATE PLOTS
%% ========================================================================

% Common axis/font settings
ax_fontsize    = 14;
label_fontsize = 18;
legend_fontsize = 12;
line_width     = 2;
line_alpha     = 0.7;

%% --- Figure 1: Carrier Density (n, p) - LOG Y-AXIS ---
if do_carrier_density
    fig1 = figure('Name', 'Carrier Density', ...
                  'Position', [50, 50, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax1 = axes(fig1);
    hold(ax1, 'on');
    
    h_lines = gobjects(numel(plot_data), 2);
    
    for i = 1:numel(plot_data)
        h_lines(i,1) = semilogy(ax1, plot_data(i).x, plot_data(i).n, '-', ...
                                'Color', [plot_data(i).color, line_alpha], ...
                                'LineWidth', line_width);
        h_lines(i,2) = semilogy(ax1, plot_data(i).x, plot_data(i).p, ':', ...
                                'Color', [plot_data(i).color, line_alpha], ...
                                'LineWidth', line_width);
    end
    
    % Build legend
    leg_handles = [h_lines(:,1); ...
                   plot(ax1, NaN, NaN, 'k-', 'LineWidth', line_width); ...
                   plot(ax1, NaN, NaN, 'k:', 'LineWidth', line_width)];
    leg_entries = [{plot_data.label}, {'n (solid)'}, {'p (dotted)'}];
    
    xlabel(ax1, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax1, 'Carrier Density (cm^{-3})', 'FontSize', label_fontsize);
    xlim(ax1, xrange);
    set(ax1, 'YScale', 'log', 'FontSize', ax_fontsize, ...
             'LineWidth', 1.2, 'Box', 'on');
    grid(ax1, 'on');
    legend(ax1, leg_handles, leg_entries, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax1, 'off');
end

%% --- Figure 2: Charge Density (rho) ---
if do_charge_density
    fig2 = figure('Name', 'Charge Density', ...
                  'Position', [100, 100, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax2 = axes(fig2);
    hold(ax2, 'on');
    
    h_lines = gobjects(numel(plot_data), 1);
    
    for i = 1:numel(plot_data)
        h_lines(i) = plot(ax2, plot_data(i).x, plot_data(i).rho, '-', ...
                          'Color', [plot_data(i).color, line_alpha], ...
                          'LineWidth', line_width);
    end
    
    xlabel(ax2, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax2, 'Charge Density (cm^{-3})', 'FontSize', label_fontsize);
    xlim(ax2, xrange);
    set(ax2, 'FontSize', ax_fontsize, 'LineWidth', 1.2, 'Box', 'on');
    grid(ax2, 'on');
    legend(ax2, h_lines, {plot_data.label}, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax2, 'off');
end

%% --- Figure 3: Electric Field (F) ---
if do_electric_field
    fig3 = figure('Name', 'Electric Field', ...
                  'Position', [150, 150, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax3 = axes(fig3);
    hold(ax3, 'on');
    
    h_lines = gobjects(numel(plot_data), 1);
    
    for i = 1:numel(plot_data)
        h_lines(i) = plot(ax3, plot_data(i).x, plot_data(i).F, '-', ...
                          'Color', [plot_data(i).color, line_alpha], ...
                          'LineWidth', line_width);
    end
    
    xlabel(ax3, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax3, 'Electric Field (V cm^{-1})', 'FontSize', label_fontsize);
    xlim(ax3, xrange);
    set(ax3, 'FontSize', ax_fontsize, 'LineWidth', 1.2, 'Box', 'on');
    grid(ax3, 'on');
    legend(ax3, h_lines, {plot_data.label}, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax3, 'off');
end

%% --- Figure 4: Electrostatic Potential (V) ---
if do_potential
    fig4 = figure('Name', 'Electrostatic Potential', ...
                  'Position', [200, 200, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax4 = axes(fig4);
    hold(ax4, 'on');
    
    h_lines = gobjects(numel(plot_data), 1);
    
    for i = 1:numel(plot_data)
        h_lines(i) = plot(ax4, plot_data(i).x, plot_data(i).V, '-', ...
                          'Color', [plot_data(i).color, line_alpha], ...
                          'LineWidth', line_width);
    end
    
    xlabel(ax4, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax4, 'Electrostatic Potential (V)', 'FontSize', label_fontsize);
    xlim(ax4, xrange);
    set(ax4, 'FontSize', ax_fontsize, 'LineWidth', 1.2, 'Box', 'on');
    grid(ax4, 'on');
    legend(ax4, h_lines, {plot_data.label}, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax4, 'off');
end

%% --- Figure 5: Band Energies (Ecb, Evb, Ef) ---
if do_band_energies
    fig5 = figure('Name', 'Band Energies', ...
                  'Position', [250, 250, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax5 = axes(fig5);
    hold(ax5, 'on');
    
    h_lines = gobjects(numel(plot_data), 3);
    
    for i = 1:numel(plot_data)
        h_lines(i,1) = plot(ax5, plot_data(i).x, plot_data(i).Ecb, '-', ...
                            'Color', [plot_data(i).color, line_alpha], ...
                            'LineWidth', line_width);
        h_lines(i,2) = plot(ax5, plot_data(i).x, plot_data(i).Evb, '-', ...
                            'Color', [plot_data(i).color, line_alpha], ...
                            'LineWidth', line_width * 0.7);
        h_lines(i,3) = plot(ax5, plot_data(i).x, plot_data(i).Efn, ':', ...
                            'Color', [plot_data(i).color, line_alpha], ...
                            'LineWidth', line_width);
    end
    
    % Build legend
    leg_handles = [h_lines(:,1); ...
                   plot(ax5, NaN, NaN, 'k-', 'LineWidth', line_width); ...
                   plot(ax5, NaN, NaN, 'k:', 'LineWidth', line_width)];
    leg_entries = [{plot_data.label}, {'E_{CB}, E_{VB} (solid)'}, ...
                   {'E_F (dotted)'}];
    
    xlabel(ax5, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax5, 'Energy (eV)', 'FontSize', label_fontsize);
    xlim(ax5, xrange);
    set(ax5, 'FontSize', ax_fontsize, 'LineWidth', 1.2, 'Box', 'on');
    grid(ax5, 'on');
    legend(ax5, leg_handles, leg_entries, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax5, 'off');
end

%% --- Figure 6: Recombination Rates (btb, SRH, vsr) ---
if do_recombination
    fig6 = figure('Name', 'Recombination Rates', ...
                  'Position', [300, 300, fig_size(1), fig_size(2)], ...
                  'Color', 'w');
    ax6 = axes(fig6);
    hold(ax6, 'on');
    
    h_lines = gobjects(numel(plot_data), 3);
    
    for i = 1:numel(plot_data)
        h_lines(i,1) = semilogy(ax6, plot_data(i).x_sub, abs(plot_data(i).r_btb), '-', ...
                                'Color', [plot_data(i).color, line_alpha], ...
                                'LineWidth', line_width);
        h_lines(i,2) = semilogy(ax6, plot_data(i).x_sub, abs(plot_data(i).r_srh), ':', ...
                                'Color', [plot_data(i).color, line_alpha], ...
                                'LineWidth', line_width);
        h_lines(i,3) = semilogy(ax6, plot_data(i).x_sub, abs(plot_data(i).r_vsr), '--', ...
                                'Color', [plot_data(i).color, line_alpha], ...
                                'LineWidth', line_width);
    end
    
    % Build legend
    leg_handles = [h_lines(:,1); ...
                   plot(ax6, NaN, NaN, 'k-', 'LineWidth', line_width); ...
                   plot(ax6, NaN, NaN, 'k:', 'LineWidth', line_width); ...
                   plot(ax6, NaN, NaN, 'k--', 'LineWidth', line_width)];
    leg_entries = [{plot_data.label}, {'r_{btb} (solid)'}, ...
                   {'r_{SRH} (dotted)'}, {'r_{vsr} (dashed)'}];
    
    xlabel(ax6, 'Position (nm)', 'FontSize', label_fontsize);
    ylabel(ax6, 'Recombination Rate (cm^{-3} s^{-1})', 'FontSize', label_fontsize);
    xlim(ax6, xrange);
    set(ax6, 'YScale', 'log', 'FontSize', ax_fontsize, ...
             'LineWidth', 1.2, 'Box', 'on');
    grid(ax6, 'on');
    legend(ax6, leg_handles, leg_entries, 'Location', 'best', ...
           'FontSize', legend_fontsize);
    
    hold(ax6, 'off');
end

fprintf('=== Generated %d figures ===\n', ...
        do_carrier_density + do_charge_density + do_electric_field + ...
        do_potential + do_band_energies + do_recombination);

end  % end main function


%% ========================================================================
%  HELPER FUNCTIONS
%% ========================================================================

function lbl = make_label(p, sweep_name)
%MAKE_LABEL Create legend label based on swept parameter

    switch sweep_name
        case "junction_depth"
            lbl = sprintf("j_d = %d nm", round(p.junction_depth));
        case "sp_r"
            lbl = sprintf("s_p = %.0e cm/s", p.sp_r);
        case "eta_sf"
            lbl = sprintf("\\eta_{SF} = %.1f", p.eta_sf);
        case "EF"
            lbl = sprintf("E_F = %.3f eV", p.EF_emitter);
        case "Phi_R_offset"
            lbl = sprintf("\\Phi_R offset = %.4f eV", p.Phi_R_offset);
        otherwise
            lbl = "run";
    end
    lbl = string(lbl);
end