function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 22-May-2024 08:55:48

% Create figure
figure('OuterPosition',[15.4 192.2 614.4 539.2]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('IQE (%)');

% Create xlabel
xlabel('Wavelength (nm)');

box(axes1,'on');
hold(axes1,'off');
